### ISSUE TITLE
Fully charge Sessy + XoM

### ISSUE THREAD

**Issue by npostman** [PimDoos/ha-sessy-examples#1]
Hey Pim..
Wilde jouw XoM blueprint file even analyseren om wat meer thuis in HA Scripting te worden, met als doel een script te maken die mijn sessys kan bijladen.. zie ik gewoon dat jij daar ook al een script blueprint voor hebt.

Ik heb dat script voorbeeld gebruikt om een variant op jouw script te maken, maar wellicht is het een idee om mijn aanpassingen als optie te implementeren.

Ik heb als extra stappen in mijn script dat ie de XoM automation stopt, en aan het einde weer start. Zo kan ik 's avonds laat de Recharge handmatig starten (of straks via een script dat de goedkoopste uren zoekt, en mbv mijn SoC en verwachte PV opbrengst de Sessys bijlaadt tot een specifieke SoC), en rustig naar bed gaan.

Is dit makkelijk toe te voegen als Input optie/configuratie?

**Comment by npostman** [comment]
En weet jij zo ook of de variabelen van een script aan te passen zijn op het moment dat je het script aanroept? Maw, kan ik dan jouw script aanroepen via een service call, en daarin de SoC en Charge Power dynamisch meegeven?

**Comment by PimDoos** [comment]
Beide kan nu :)
- Het script heeft nu een start en end action in de configuratie, die respectievelijk bij de start en eind van het laadproces worden uitgevoerd
- Je kunt `charge_power` en `battery_soc_max` overriden via de data parameter van de service call:

```yaml
service: script.sessy_full_charge
data: 
  battery_soc_max: 80
  charge_power: 2000
```

**Comment by npostman** [comment]
Geniaal. Thanks!
