### ISSUE TITLE
Dynamic schedule / Epex + provider uplift

### ISSUE THREAD

**Issue by dacootmeister** [PimDoos/ha-sessy-examples#11]
Hi Pim,

Would it be possible to use a sensor for actual prices (epex+provider uplift in the Dynamic schedule ApexChart Cards? (https://github.com/PimDoos/ha-sessy-examples/blob/main/cards/DynamicSchedule.md)
Including my own sensor "sensor.zonneplan_energyprices" gives no result in the ApexChart card as the script probably relies on Sessy's own API data

**Comment by PimDoos** [comment]
You would probably need to tweak the data generator for the Energy Price series to match your sensor's format. This card configuration is built mainly to use the data format provided by Sessy.

**Comment by dacootmeister** [comment]
understood
