### ISSUE TITLE
Error in creating script from Charge blueprint

### ISSUE THREAD

**Issue by npostman** [PimDoos/ha-sessy-examples#2]
Hey Pim,
Ik maakte net een nieuw script aan obv jouw vernieuwde blueprint en kreeg de volgende error:

Message malformed: expected a dictionary for dictionary value @ data['sequence'][1]['then'][0]['variables']

Ik heb ingesteld:

Name
Icon
Selected 2 sessys
Charge power 3000
Timeout 3 hours
Start action: automation.turn_off -> automation.sessy_xom
End action: automation.turn_on -> automation.sessy_xom
End strategy: API

Enig idee what's up>?

Thanks,
Niels

**Comment by PimDoos** [comment]
Foutje bij het implementeren van de nieuwe functies uit #1, had blijkbaar de nieuwe versie niet goed naar de testomgeving uitgerold. Zou nu moeten werken!
