### ISSUE TITLE
Error in Execution Charge script

### ISSUE THREAD

**Issue by npostman** [PimDoos/ha-sessy-examples#3]
Hey Pim,
Sorry hoor.. ik blijf je lastig vallen.. Heb jij het Fully Charge script werkend? Ik kon de nieuwe versie wel installeren en er een script van maken, maar bij het uitvoeren gaat ie stuk:\

Error: UndefinedError: 'charge_power' is undefined

Heb em wel ingesteld in het script. Kan ik jou iets uit de Trace sturen waar je iets mee kan?

**Comment by npostman** [comment]
Snap er met mijn HA noob kennis niks van. Heb geprobeerd wat research te doen, en te kijken of ik je een PR kon bieden, maar helaas. Ben echt nog té nat achter de oren.

Is dit misschien iets? [https://www.home-assistant.io/docs/scripts/#scope-of-variables](variables scope)

**Comment by PimDoos** [comment]
Ik vermoed dat de versie op Github niet helemaal overeen komt met de versie in mijn testomgeving. Ik zal vanavond nog eens een nieuwe versie pushen

**Comment by PimDoos** [comment]
Check eens of het wel werkt na 1369bc5 ?

**Comment by npostman** [comment]
Stand-alone werkt het script. Zal nu eens kijken met input van buiten het script..

Viel me trouwens net op dat ik het script startte met een target SoC van 80% en dat ie wel meteen begon te laden op beide accu's, terwijl de SoC van beide nog boven de 80% zat. Zou ie dat niet moeten oppikken? En dus niks doen?
Je checkt wel op de SoC in je script, om hem op de max_soc te laten stoppen, toch?

**Comment by npostman** [comment]
Ik kan de charge power inderdaad van buiten het script als data meegeven, alleen de battery_soc_max krijg ik niet werkend, althans, het lijkt alsof ie deze niet respecteert of goed afhandeld in de blueprint.

**Comment by PimDoos** [comment]
De battery_soc_max wordt alleen gecheckt na het starten van een charge, ik kan me een paar situaties bedenken waarin de huidige opzet vreemd gedrag kan opleveren:
- Als de batterij al voorbij dit percentage is als je begint met laden (gaat door tot battery_full)
- Als je meerdere Sessy's hebt en het percentage verschilt per batterij (stopt pas als beide > battery_soc_max zijn)

**Comment by npostman** [comment]
Hmm.. Ik snap wat je bedoelt. Zou je bij het starten van het script niet de device_ids kunnen checken of huidige SoC groter is dan target SoC en ze er dan uitgooien?

En om bij meerdere Sessys de Sessy met voldoende SoC te laten stoppen met laden, heb je een ingewikkelder script (of automation) nodig, of niet?

Sluit deze issue maar als het te ver gaat voor dit script. Dan ga ik zelf even prutsen aan een eigen automation oid..
