### ISSUE TITLE
Sessy v0.5.5 code  issue Sensor - Charge power 

### ISSUE THREAD

**Issue by dacootmeister** [PimDoos/ha-sessy-examples#4]
Hi Pim,

I've seen an issue with one of my 2 Sessy's sensor values.
My left Sessy reports Charge power Onbekend
<img width="738" alt="sessy links" src="https://github.com/PimDoos/ha-sessy-examples/assets/35705080/ea5bf51d-9652-43cd-b924-4420c21356c2">
and the right one Charge power 0 kWh
<img width="734" alt="sessy rechts" src="https://github.com/PimDoos/ha-sessy-examples/assets/35705080/77c4f426-18db-43f2-aa1c-1578de9620ef">

This results in an Energy Dashboard with uknown values:
sensor.sessy_battery_links_discharge_power (unknown)
sensor.sessy_battery_links_charge_power (unknown)
<img width="379" alt="battery" src="https://github.com/PimDoos/ha-sessy-examples/assets/35705080/4f24d19f-c075-4865-99d2-e76c7acf8fe7">

Any idea how to fix this?

**Comment by npostman** [comment]
Have you checked your connectivity? Access your Sessys internal web UI and see if you get any errors.

And what does accessing <IP>/api/v1/power/status give you?
Maybe restart your Sessys by turning off the power supply for a little bit.

**Comment by dacootmeister** [comment]
> v1/power/status

Connectivity is fine, already checked that using web interface and rebooted the dongle via HA.
Outcome of the API query:
{
	"status":	"ok",
	"sessy":	{
		"state_of_charge":	0,
		"power":	0,
		"power_setpoint":	0,
		"system_state":	"SYSTEM_STATE_STANDBY",
		"system_state_details":	"",
		"frequency":	49975
	},
	"renewable_energy_phase1":	{
		"voltage_rms":	229989,
		"current_rms":	214,
		"power":	49
	},
	"renewable_energy_phase2":	{
		"voltage_rms":	0,
		"current_rms":	0,
		"power":	0
	},
	"renewable_energy_phase3":	{
		"voltage_rms":	0,
		"current_rms":	0,
		"power":	0
	}
}
