### ISSUE TITLE
XoM, but charge or discharge only

### ISSUE THREAD

**Issue by npostman** [PimDoos/ha-sessy-examples#5]
Hey Pim,

Is it an idea to add some kind of customizable flag to set some kind of xom mode, like 'Charge-' or 'Discharge-only'?

Some days during the cheap 'sunny' hours I want to run XoM but only charge (so only compensate the negative P1), and when I turn on the washing machine, don't pull it out of the sessy, but the net. Then during expensive hours, I want to only compensate positive P1 values, so pull usage from the sessy, and allow any production to go to the net (getting the better value for it)..

Do you catch my drift?

Niels

**Comment by PimDoos** [comment]
Interesting idea. I'll have a look whether I want to integrate this into the existing blueprint or branch off to a separate one.

**Comment by npostman** [comment]
Hi Pim.. any chance you could have a look at this? On a sunny day like this I'd like to save my solar power for this evening.. so in a perfect world it would only compensate when the target setpoint is negative.. when positive it should go to 0, so any requested power comes from the net, and not my battery.
I'm thinking of some kind of select list helper, or at least a configurable setting that you can update with scripts or automations.

**Comment by PimDoos** [comment]
I think this could be implemented in a more versatile way by providing the script with min/max setpoint variables. This way you can create multiple automations:
- Automation 'XOM Charge' with maximum setpoint of 0 and minimum of -2200 * num_sessy
- Automation 'XOM Discharge' with a minimum setpoint of 0 and a maximum of 2200 * num_sessy
- A third automation to choose which XOM automation to activated based on your criteria

**Comment by PimDoos** [comment]
Latest version contains the proposed min/max power setpoint controls. With the default values, the behaviour is unchanged. Could you test this and see if it helps with your usecase?

**Comment by npostman** [comment]
Thanks Pim. I’ll have a go with this and will let you know.
