### ISSUE TITLE
Could you explain this part of the script?

### ISSUE THREAD

**Issue by npostman** [PimDoos/ha-sessy-examples#6]
https://github.com/PimDoos/ha-sessy-examples/blob/1369bc557be70edbd6d0f4bcf87a17f56d592d52/blueprints/script/sessy/sessy-full-charge.yaml#L137-L141

Hey Pim,

I used this part in a little bit altered script, but when both of my Sessys are full, this trigger does not fire, and I try to find out why. The script stops because of the timeout value, not because both states are 'battery_full'.

Can you briefly explain what you/the script does here?

Thanks in advance,
Niels

**Comment by PimDoos** [comment]
I was going to say: Try out the HA DevTools to see when it returns true. But...
I think I found a mistake. There should be an `and` operator in the template which adds both checks together. So this is definitely a bug in the script 🤐
